package com.aaronhible.model;

// Generated Dec 12, 2012 8:51:28 AM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * CustomerDemographic generated by hbm2java
 */
public class CustomerDemographic implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String customerTypeId;
	private String customerDesc;
	private Set<Customer> customerses = new HashSet<Customer>(0);

	public CustomerDemographic() {
	}

	public CustomerDemographic(String customerTypeId) {
		this.customerTypeId = customerTypeId;
	}

	public CustomerDemographic(String customerTypeId, String customerDesc,
			Set<Customer> customerses) {
		this.customerTypeId = customerTypeId;
		this.customerDesc = customerDesc;
		this.customerses = customerses;
	}

	public String getCustomerTypeId() {
		return this.customerTypeId;
	}

	public void setCustomerTypeId(String customerTypeId) {
		this.customerTypeId = customerTypeId;
	}

	public String getCustomerDesc() {
		return this.customerDesc;
	}

	public void setCustomerDesc(String customerDesc) {
		this.customerDesc = customerDesc;
	}

	public Set<Customer> getCustomerses() {
		return this.customerses;
	}

	public void setCustomerses(Set<Customer> customerses) {
		this.customerses = customerses;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((customerTypeId == null) ? 0 : customerTypeId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CustomerDemographic other = (CustomerDemographic) obj;
		if (customerTypeId == null) {
			if (other.customerTypeId != null)
				return false;
		} else if (!customerTypeId.equals(other.customerTypeId))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "CustomerDemographic [customerTypeId=" + customerTypeId
				+ ", customerDesc=" + customerDesc + ", customerses="
				+ customerses + "]";
	}

}
