package com.aaronhible.model;

// Generated Dec 12, 2012 8:51:28 AM by Hibernate Tools 3.2.2.GA

import java.sql.Clob;
import java.util.HashSet;
import java.util.Set;

/**
 * CustomerDemographics generated by hbm2java
 */
public class CustomerDemographics implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String customerTypeId;
	private Clob customerDesc;
	private Set<Customers> customerses = new HashSet<Customers>(0);

	public CustomerDemographics() {
	}

	public CustomerDemographics(String customerTypeId) {
		this.customerTypeId = customerTypeId;
	}

	public CustomerDemographics(String customerTypeId, Clob customerDesc,
			Set<Customers> customerses) {
		this.customerTypeId = customerTypeId;
		this.customerDesc = customerDesc;
		this.customerses = customerses;
	}

	public String getCustomerTypeId() {
		return this.customerTypeId;
	}

	public void setCustomerTypeId(String customerTypeId) {
		this.customerTypeId = customerTypeId;
	}

	public Clob getCustomerDesc() {
		return this.customerDesc;
	}

	public void setCustomerDesc(Clob customerDesc) {
		this.customerDesc = customerDesc;
	}

	public Set<Customers> getCustomerses() {
		return this.customerses;
	}

	public void setCustomerses(Set<Customers> customerses) {
		this.customerses = customerses;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((customerTypeId == null) ? 0 : customerTypeId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CustomerDemographics other = (CustomerDemographics) obj;
		if (customerTypeId == null) {
			if (other.customerTypeId != null)
				return false;
		} else if (!customerTypeId.equals(other.customerTypeId))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "CustomerDemographics [customerTypeId=" + customerTypeId
				+ ", customerDesc=" + customerDesc + ", customerses="
				+ customerses + "]";
	}
	
}
