package com.aaronhible.model;

// Generated Dec 12, 2012 8:51:28 AM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Shipper generated by hbm2java
 */
public class Shipper implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String companyName;
	private String phone;
	private Set<Order> orders = new HashSet<Order>(0);

	public Shipper() {
	}

	public Shipper(int id, String companyName) {
		this.id = id;
		this.companyName = companyName;
	}

	public Shipper(int shipperId, String companyName, String phone,
			Set<Order> orders) {
		this.id = shipperId;
		this.companyName = companyName;
		this.phone = phone;
		this.orders = orders;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Shipper other = (Shipper) obj;
		if (id != other.id)
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Shipper [id=" + id + ", companyName=" + companyName
				+ ", phone=" + phone + ", orders=" + orders + "]";
	}

}
