package com.aaronhible.model;

// Generated Dec 12, 2012 8:51:28 AM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Territories generated by hbm2java
 */
public class Territories implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String territoryId;
	private Region region;
	private String territoryDescription;
	private Set<Employees> employeeses = new HashSet<Employees>(0);

	public Territories() {
	}

	public Territories(String territoryId, Region region,
			String territoryDescription) {
		this.territoryId = territoryId;
		this.region = region;
		this.territoryDescription = territoryDescription;
	}

	public Territories(String territoryId, Region region,
			String territoryDescription, Set<Employees> employeeses) {
		this.territoryId = territoryId;
		this.region = region;
		this.territoryDescription = territoryDescription;
		this.employeeses = employeeses;
	}

	public String getTerritoryId() {
		return this.territoryId;
	}

	public void setTerritoryId(String territoryId) {
		this.territoryId = territoryId;
	}

	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	public String getTerritoryDescription() {
		return this.territoryDescription;
	}

	public void setTerritoryDescription(String territoryDescription) {
		this.territoryDescription = territoryDescription;
	}

	public Set<Employees> getEmployeeses() {
		return this.employeeses;
	}

	public void setEmployeeses(Set<Employees> employeeses) {
		this.employeeses = employeeses;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((territoryId == null) ? 0 : territoryId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Territories other = (Territories) obj;
		if (territoryId == null) {
			if (other.territoryId != null)
				return false;
		} else if (!territoryId.equals(other.territoryId))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Territories [territoryId=" + territoryId + ", region=" + region
				+ ", territoryDescription=" + territoryDescription
				+ ", employeeses=" + employeeses + "]";
	}

}
