package com.aaronhible.model.views;
// Generated Dec 12, 2012 8:51:28 AM by Hibernate Tools 3.2.2.GA



/**
 * AlphabeticalListOfProducts generated by hbm2java
 */
public class AlphabeticalListOfProducts  implements java.io.Serializable {


     private AlphabeticalListOfProductsId id;

    public AlphabeticalListOfProducts() {
    }

    public AlphabeticalListOfProducts(AlphabeticalListOfProductsId id) {
       this.id = id;
    }
   
    public AlphabeticalListOfProductsId getId() {
        return this.id;
    }
    
    public void setId(AlphabeticalListOfProductsId id) {
        this.id = id;
    }




}


