package com.aaronhible.model.views;
// Generated Dec 12, 2012 8:51:28 AM by Hibernate Tools 3.2.2.GA



/**
 * CategorySalesFor1997 generated by hbm2java
 */
public class CategorySalesFor1997  implements java.io.Serializable {


     private CategorySalesFor1997Id id;

    public CategorySalesFor1997() {
    }

    public CategorySalesFor1997(CategorySalesFor1997Id id) {
       this.id = id;
    }
   
    public CategorySalesFor1997Id getId() {
        return this.id;
    }
    
    public void setId(CategorySalesFor1997Id id) {
        this.id = id;
    }




}


