package com.aaronhible.model.views;
// Generated Dec 12, 2012 8:51:28 AM by Hibernate Tools 3.2.2.GA



/**
 * CurrentProductListId generated by hbm2java
 */
public class CurrentProductListId  implements java.io.Serializable {


     private int productId;
     private String productName;

    public CurrentProductListId() {
    }

    public CurrentProductListId(int productId, String productName) {
       this.productId = productId;
       this.productName = productName;
    }
   
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }




}


