package com.aaronhible.model.views;
// Generated Dec 12, 2012 8:51:28 AM by Hibernate Tools 3.2.2.GA



/**
 * CurrentProductList generated by hbm2java
 */
public class CurrentProductList  implements java.io.Serializable {


     private CurrentProductListId id;

    public CurrentProductList() {
    }

    public CurrentProductList(CurrentProductListId id) {
       this.id = id;
    }
   
    public CurrentProductListId getId() {
        return this.id;
    }
    
    public void setId(CurrentProductListId id) {
        this.id = id;
    }




}


