package com.aaronhible.model.views;
// Generated Dec 12, 2012 8:51:28 AM by Hibernate Tools 3.2.2.GA



/**
 * CustomerAndSuppliersByCityId generated by hbm2java
 */
public class CustomerAndSuppliersByCityId  implements java.io.Serializable {


     private String city;
     private String companyName;
     private String contactName;
     private String relationship;

    public CustomerAndSuppliersByCityId() {
    }

    public CustomerAndSuppliersByCityId(String city, String companyName, String contactName, String relationship) {
       this.city = city;
       this.companyName = companyName;
       this.contactName = contactName;
       this.relationship = relationship;
    }
   
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public String getContactName() {
        return this.contactName;
    }
    
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }
    public String getRelationship() {
        return this.relationship;
    }
    
    public void setRelationship(String relationship) {
        this.relationship = relationship;
    }




}


