package com.aaronhible.model.views;
// Generated Dec 12, 2012 8:51:28 AM by Hibernate Tools 3.2.2.GA



/**
 * CustomerAndSuppliersByCity generated by hbm2java
 */
public class CustomerAndSuppliersByCity  implements java.io.Serializable {


     private CustomerAndSuppliersByCityId id;

    public CustomerAndSuppliersByCity() {
    }

    public CustomerAndSuppliersByCity(CustomerAndSuppliersByCityId id) {
       this.id = id;
    }
   
    public CustomerAndSuppliersByCityId getId() {
        return this.id;
    }
    
    public void setId(CustomerAndSuppliersByCityId id) {
        this.id = id;
    }




}


