package com.aaronhible.model.views;
// Generated Dec 12, 2012 8:51:28 AM by Hibernate Tools 3.2.2.GA



/**
 * Invoices generated by hbm2java
 */
public class Invoices  implements java.io.Serializable {


     private InvoicesId id;

    public Invoices() {
    }

    public Invoices(InvoicesId id) {
       this.id = id;
    }
   
    public InvoicesId getId() {
        return this.id;
    }
    
    public void setId(InvoicesId id) {
        this.id = id;
    }




}


