package com.aaronhible.model.views;
// Generated Dec 12, 2012 8:51:28 AM by Hibernate Tools 3.2.2.GA



/**
 * OrderDetailsExtended generated by hbm2java
 */
public class OrderDetailsExtended  implements java.io.Serializable {


     private OrderDetailsExtendedId id;

    public OrderDetailsExtended() {
    }

    public OrderDetailsExtended(OrderDetailsExtendedId id) {
       this.id = id;
    }
   
    public OrderDetailsExtendedId getId() {
        return this.id;
    }
    
    public void setId(OrderDetailsExtendedId id) {
        this.id = id;
    }




}


