package com.aaronhible.model.views;
// Generated Dec 12, 2012 8:51:28 AM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * OrderSubtotalsId generated by hbm2java
 */
public class OrderSubtotalsId  implements java.io.Serializable {


     private int orderId;
     private BigDecimal subtotal;

    public OrderSubtotalsId() {
    }

    public OrderSubtotalsId(int orderId, BigDecimal subtotal) {
       this.orderId = orderId;
       this.subtotal = subtotal;
    }
   
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }




}


