package com.aaronhible.model.views;
// Generated Dec 12, 2012 8:51:28 AM by Hibernate Tools 3.2.2.GA



/**
 * OrderSubtotals generated by hbm2java
 */
public class OrderSubtotals  implements java.io.Serializable {


     private OrderSubtotalsId id;

    public OrderSubtotals() {
    }

    public OrderSubtotals(OrderSubtotalsId id) {
       this.id = id;
    }
   
    public OrderSubtotalsId getId() {
        return this.id;
    }
    
    public void setId(OrderSubtotalsId id) {
        this.id = id;
    }




}


