package com.aaronhible.model.views;
// Generated Dec 12, 2012 8:51:28 AM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * OrderDetailsExtendedId generated by hbm2java
 */
public class OrderDetailsExtendedId  implements java.io.Serializable {


     private int orderId;
     private int productId;
     private String productName;
     private BigDecimal unitPrice;
     private short quantity;
     private float discount;
     private BigDecimal extendedPrice;

    public OrderDetailsExtendedId() {
    }

    public OrderDetailsExtendedId(int orderId, int productId, String productName, BigDecimal unitPrice, short quantity, float discount, BigDecimal extendedPrice) {
       this.orderId = orderId;
       this.productId = productId;
       this.productName = productName;
       this.unitPrice = unitPrice;
       this.quantity = quantity;
       this.discount = discount;
       this.extendedPrice = extendedPrice;
    }
   
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }
    public short getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(short quantity) {
        this.quantity = quantity;
    }
    public float getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(float discount) {
        this.discount = discount;
    }
    public BigDecimal getExtendedPrice() {
        return this.extendedPrice;
    }
    
    public void setExtendedPrice(BigDecimal extendedPrice) {
        this.extendedPrice = extendedPrice;
    }




}


