package com.aaronhible.model.views;
// Generated Dec 12, 2012 8:51:28 AM by Hibernate Tools 3.2.2.GA



/**
 * OrdersQry generated by hbm2java
 */
public class OrdersQry  implements java.io.Serializable {


     private OrdersQryId id;

    public OrdersQry() {
    }

    public OrdersQry(OrdersQryId id) {
       this.id = id;
    }
   
    public OrdersQryId getId() {
        return this.id;
    }
    
    public void setId(OrdersQryId id) {
        this.id = id;
    }




}


