package com.aaronhible.model.views;
// Generated Dec 12, 2012 8:51:28 AM by Hibernate Tools 3.2.2.GA



/**
 * ProductSalesFor1997 generated by hbm2java
 */
public class ProductSalesFor1997  implements java.io.Serializable {


     private ProductSalesFor1997Id id;

    public ProductSalesFor1997() {
    }

    public ProductSalesFor1997(ProductSalesFor1997Id id) {
       this.id = id;
    }
   
    public ProductSalesFor1997Id getId() {
        return this.id;
    }
    
    public void setId(ProductSalesFor1997Id id) {
        this.id = id;
    }




}


