package com.aaronhible.model.views;
// Generated Dec 12, 2012 8:51:28 AM by Hibernate Tools 3.2.2.GA



/**
 * ProductsByCategory generated by hbm2java
 */
public class ProductsByCategory  implements java.io.Serializable {


     private ProductsByCategoryId id;

    public ProductsByCategory() {
    }

    public ProductsByCategory(ProductsByCategoryId id) {
       this.id = id;
    }
   
    public ProductsByCategoryId getId() {
        return this.id;
    }
    
    public void setId(ProductsByCategoryId id) {
        this.id = id;
    }




}


