package com.aaronhible.model.views;
// Generated Dec 12, 2012 8:51:28 AM by Hibernate Tools 3.2.2.GA



/**
 * ProductsByCategoryId generated by hbm2java
 */
public class ProductsByCategoryId  implements java.io.Serializable {


     private String categoryName;
     private String productName;
     private String quantityPerUnit;
     private Short unitsInStock;
     private boolean discontinued;

    public ProductsByCategoryId() {
    }

    public ProductsByCategoryId(String categoryName, String productName, String quantityPerUnit, Short unitsInStock, boolean discontinued) {
       this.categoryName = categoryName;
       this.productName = productName;
       this.quantityPerUnit = quantityPerUnit;
       this.unitsInStock = unitsInStock;
       this.discontinued = discontinued;
    }
   
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public String getQuantityPerUnit() {
        return this.quantityPerUnit;
    }
    
    public void setQuantityPerUnit(String quantityPerUnit) {
        this.quantityPerUnit = quantityPerUnit;
    }
    public Short getUnitsInStock() {
        return this.unitsInStock;
    }
    
    public void setUnitsInStock(Short unitsInStock) {
        this.unitsInStock = unitsInStock;
    }
    public boolean isDiscontinued() {
        return this.discontinued;
    }
    
    public void setDiscontinued(boolean discontinued) {
        this.discontinued = discontinued;
    }




}


