package com.aaronhible.model.views;
// Generated Dec 12, 2012 8:51:28 AM by Hibernate Tools 3.2.2.GA



/**
 * ProductsAboveAveragePrice generated by hbm2java
 */
public class ProductsAboveAveragePrice  implements java.io.Serializable {


     private ProductsAboveAveragePriceId id;

    public ProductsAboveAveragePrice() {
    }

    public ProductsAboveAveragePrice(ProductsAboveAveragePriceId id) {
       this.id = id;
    }
   
    public ProductsAboveAveragePriceId getId() {
        return this.id;
    }
    
    public void setId(ProductsAboveAveragePriceId id) {
        this.id = id;
    }




}


