package com.aaronhible.model.views;
// Generated Dec 12, 2012 8:51:28 AM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * ProductSalesFor1997Id generated by hbm2java
 */
public class ProductSalesFor1997Id  implements java.io.Serializable {


     private String categoryName;
     private String productName;
     private BigDecimal productSales;

    public ProductSalesFor1997Id() {
    }

    public ProductSalesFor1997Id(String categoryName, String productName, BigDecimal productSales) {
       this.categoryName = categoryName;
       this.productName = productName;
       this.productSales = productSales;
    }
   
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public BigDecimal getProductSales() {
        return this.productSales;
    }
    
    public void setProductSales(BigDecimal productSales) {
        this.productSales = productSales;
    }




}


