package com.aaronhible.model.views;
// Generated Dec 12, 2012 8:51:28 AM by Hibernate Tools 3.2.2.GA



/**
 * QuarterlyOrdersId generated by hbm2java
 */
public class QuarterlyOrdersId  implements java.io.Serializable {


     private String customerId;
     private String companyName;
     private String city;
     private String country;

    public QuarterlyOrdersId() {
    }

    public QuarterlyOrdersId(String customerId, String companyName, String city, String country) {
       this.customerId = customerId;
       this.companyName = companyName;
       this.city = city;
       this.country = country;
    }
   
    public String getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }




}


