package com.aaronhible.model.views;
// Generated Dec 12, 2012 8:51:28 AM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * SalesByCategoryId generated by hbm2java
 */
public class SalesByCategoryId  implements java.io.Serializable {


     private int categoryId;
     private String categoryName;
     private String productName;
     private BigDecimal productSales;

    public SalesByCategoryId() {
    }

    public SalesByCategoryId(int categoryId, String categoryName, String productName, BigDecimal productSales) {
       this.categoryId = categoryId;
       this.categoryName = categoryName;
       this.productName = productName;
       this.productSales = productSales;
    }
   
    public int getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public BigDecimal getProductSales() {
        return this.productSales;
    }
    
    public void setProductSales(BigDecimal productSales) {
        this.productSales = productSales;
    }




}


