package com.aaronhible.model.views;
// Generated Dec 12, 2012 8:51:28 AM by Hibernate Tools 3.2.2.GA



/**
 * SalesTotalsByAmount generated by hbm2java
 */
public class SalesTotalsByAmount  implements java.io.Serializable {


     private SalesTotalsByAmountId id;

    public SalesTotalsByAmount() {
    }

    public SalesTotalsByAmount(SalesTotalsByAmountId id) {
       this.id = id;
    }
   
    public SalesTotalsByAmountId getId() {
        return this.id;
    }
    
    public void setId(SalesTotalsByAmountId id) {
        this.id = id;
    }




}


