package com.aaronhible.model.views;
// Generated Dec 12, 2012 8:51:28 AM by Hibernate Tools 3.2.2.GA



/**
 * SalesByCategory generated by hbm2java
 */
public class SalesByCategory  implements java.io.Serializable {


     private SalesByCategoryId id;

    public SalesByCategory() {
    }

    public SalesByCategory(SalesByCategoryId id) {
       this.id = id;
    }
   
    public SalesByCategoryId getId() {
        return this.id;
    }
    
    public void setId(SalesByCategoryId id) {
        this.id = id;
    }




}


