package com.aaronhible.model.views;
// Generated Dec 12, 2012 8:51:28 AM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * SalesTotalsByAmountId generated by hbm2java
 */
public class SalesTotalsByAmountId  implements java.io.Serializable {


     private BigDecimal saleAmount;
     private int orderId;
     private String companyName;
     private Date shippedDate;

    public SalesTotalsByAmountId() {
    }

    public SalesTotalsByAmountId(BigDecimal saleAmount, int orderId, String companyName, Date shippedDate) {
       this.saleAmount = saleAmount;
       this.orderId = orderId;
       this.companyName = companyName;
       this.shippedDate = shippedDate;
    }
   
    public BigDecimal getSaleAmount() {
        return this.saleAmount;
    }
    
    public void setSaleAmount(BigDecimal saleAmount) {
        this.saleAmount = saleAmount;
    }
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public Date getShippedDate() {
        return this.shippedDate;
    }
    
    public void setShippedDate(Date shippedDate) {
        this.shippedDate = shippedDate;
    }




}


