package com.aaronhible.model.views;
// Generated Dec 12, 2012 8:51:28 AM by Hibernate Tools 3.2.2.GA



/**
 * SummaryOfSalesByYear generated by hbm2java
 */
public class SummaryOfSalesByYear  implements java.io.Serializable {


     private SummaryOfSalesByYearId id;

    public SummaryOfSalesByYear() {
    }

    public SummaryOfSalesByYear(SummaryOfSalesByYearId id) {
       this.id = id;
    }
   
    public SummaryOfSalesByYearId getId() {
        return this.id;
    }
    
    public void setId(SummaryOfSalesByYearId id) {
        this.id = id;
    }




}


